### ISSUE TITLE
Code Updates

### ISSUE THREAD

**Issue by TomDonoghue** [voytekresearch/EEGMapping#6]
Vocabulary:
- [x] V1) Update 'slope' -> 'exponent'

Code Style
- [x] S1) Indent levels. Each code indent should step in by 4 spaces (one tab level), and not more.
- [x] S2) Order of imports (standard, anaconda things, custom code)

Documentation:
- [x] D1) Make sure if/when you copy paste docs that you update to only keep relevant arguments
- [x] D2) Wherever you reference / use these data structs (dicts or 3 or 4D arrays), copy in the quick description of the dimensions. 

Notebooks:
- [x] N1) Re-run notebooks with relevant print outs

Note: check through these things for other files, but here's where I see things that need doing:
- [x] scripts/analysis_eeg_dat: V1, S1, S1
- [x] notebooks/analysis.py: D1
- [x] notebooks/utilities.py: D2
- [x] notebooks/GroupAnalysis.ipynb: N1

Add these things to dev branch, and we can merge as a code overview update.

**Comment by LuyandaMdanda** [comment]
Complete, to be reviewed in PR
